export const LOAD_POST_REQUEST = "LOAD_POST_REQUEST";
export const LOAD_POST_SUCCESS = "LOAD_POST_SUCCESS";
export const LOAD_POST_FAILURE = "LOAD_POST_FAILURE";

export const ADD_POST_REQUEST = "ADD_POST_REQUEST";
export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS";
export const ADD_POST_FAILURE = "ADD_POST_FAILURE";

export const ADD_COMMENTS_REQUEST = "ADD_COMMENTS_REQUEST";
export const ADD_COMMENTS_SUCCESS = "ADD_COMMENTS_SUCCESS";
export const ADD_COMMENTS_FAILURE = "ADD_COMMENTS_FAILURE";

export const ADD_POST_TO_ME = "ADD_POST_TO_ME";
export const REMOVE_POST_OF_ME = "REMOVE_POST_OF_ME";

export const REMOVE_POST_REQUEST = "REMOVE_POST_REQUEST";
export const REMOVE_POST_SUCCESS = "REMOVE_POST_SUCCESS";
export const REMOVE_POST_FAILURE = "REMOVE_POST_FAILURE";

export const LIKE_BUTTON_REQUEST = "LIKE_BUTTON_REQUEST";
export const LIKE_BUTTON_SUCCESS = "LIKE_BUTTON_SUCCESS";
export const LIKE_BUTTON_FAILURE = "LIKE_BUTTON_FAILURE";

export const UNLIKE_BUTTON_REQUEST = "UNLIKE_BUTTON_REQUEST";
export const UNLIKE_BUTTON_SUCCESS = "UNLIKE_BUTTON_SUCCESS";
export const UNLIKE_BUTTON_FAILURE = "UNLIKE_BUTTON_FAILURE";
